query GetUserFollowers($userId: String!) {
	user: GetUser(id: $userId) {
		id
		userName
	}

	followers: GetFollowers(id: $userId) {
		id
		userId
		followingUserId
		user: GetUserByFollowing {
			id
			userName
			profileBody
			iconPhoto
		}
	}
}
