query GetUserFollowings($userId: String!) {
	user: GetUser(id: $userId) {
		id
		userName
	}

	followings: GetFollowings(id: $userId) {
		id
		userId
		followingUserId
		user: GetUserByFollower {
			id
			userName
			profileBody
			iconPhoto
			createdAt
		}
	}
}
