query GetUserTweets($userId: String!) {
	user: GetUser(id: $userId) {
		id
		userName
		profileBody
		iconPhoto
		followerCount: GetFollowerCount {
			count
		}
		followingCount: GetFollowingCount {
			count
		}
	}

	tweets: GetTweetsByUser(id: $userId) {
		id
		userId
		tweetBody
		createdAt
		user: GetUserByTweet {
			id
			userName
			profileBody
			iconPhoto
		}
		retweetCount: GetRetweetCount {
			count
		}
		likeCount: GetLikeCount {
			count
		}
		commentCount: GetCommentCount {
			count
		}
	}
}
