query GetUserTweets($userId: String!) {
	tweets: GetTweetsByUser(id: $userId) {
		id
		userId
		tweetBody
		createdAt
		user: GetUserByTweet {
			id
			userName
			profileBody
			iconPhoto
		}
		retweetCount: GetRetweetCount {
			count
		}
		likeCount: GetLikeCount {
			count
		}
		commentCount: GetCommentCount {
			count
		}
	}
}
