query GetUserLikes($userId: String!) {
	user: GetUser(id: $userId) {
		id
		userName
		profileBody
		iconPhoto
		followerCount: GetFollowerCount {
			count
		}
		followingCount: GetFollowingCount {
			count
		}
	}

	likes: GetLikesByUser(id: $userId) {
		tweet: GetTweetByLike {
			id
			userId
			tweetBody
			createdAt
			user: GetUserByTweet {
				id
				userName
				profileBody
				iconPhoto
				isFollow: GetIsFollowByUser(userId: $userId)
			}
			isRetweet: GetIsRetweetByUser(userId: $userId)
			isLike: GetIsLikeByUser(userId: $userId)
			retweetCount: GetRetweetCount {
				count
			}
			likeCount: GetLikeCount {
				count
			}
			commentCount: GetCommentCount {
				count
			}
		}
	}
}
