query GetUserRetweets($userId: String!) {
	retweets: GetRetweetsByUser(id: $userId) {
		tweet: GetTweetByRetweet {
			id
			tweetBody
			createdAt
			user: GetUserByTweet {
				id
				userName
				profileBody
				iconPhoto
			}
			retweetCount: GetRetweetCount {
				count
			}
			likeCount: GetLikeCount {
				count
			}
			commentCount: GetCommentCount {
				count
			}
		}
	}
}
