# query GetFollowingUserTweets($userId: String!) {
# 	followings: GetFollowings(id: $userId) {
# 		user: GetUserByFollower {
# 			tweets: GetTweetsByUser {
# 				id
# 				tweetBody
# 				createdAt
# 				user: GetUserByTweet {
# 					id
# 					userName
# 					iconPhoto
# 				}
# 				retweetCount: GetRetweetCount {
# 					count
# 				}
# 				likeCount: GetLikeCount {
# 					count
# 				}
# 				commentCount: GetCommentCount {
# 					count
# 				}
# 			}
# 		}
# 	}
# }

query GetAllUserTweets($userId: String!) {
	tweets: GetTweets {
		id
		userId
		tweetBody
		createdAt
		user: GetUserByTweet {
			id
			userName
			profileBody
			iconPhoto
			isFollow: GetIsFollowByUser(userId: $userId)
		}
		isRetweet: GetIsRetweetByUser(userId: $userId)
		isLike: GetIsLikeByUser(userId: $userId)
		retweetCount: GetRetweetCount {
			count
		}
		likeCount: GetLikeCount {
			count
		}
		commentCount: GetCommentCount {
			count
		}
	}
}

mutation DeleteTweet($tweetId: Int!) {
	result: DeleteTweet(id: $tweetId)
}
