query GetFollowingUserTweets($userId: String!) {
	followings: GetFollowings(id: $userId) {
		user: GetUserByFollower {
			tweets: GetTweetsByUser {
				id
				tweetBody
				createdAt
				user: GetUserByTweet {
					id
					userName
					iconPhoto
				}
				retweetCount: GetRetweetCount {
					count
				}
				likeCount: GetLikeCount {
					count
				}
				commentCount: GetCommentCount {
					count
				}
			}
		}
	}
}

mutation DeleteTweet($tweetId: Int!) {
	result: DeleteTweet(id: $tweetId)
}
