query GetTweetDetail($tweetId: Int!, $userId: String!) {
	tweet: GetTweet(id: $tweetId) {
		id
		userId
		tweetBody
		createdAt
		user: GetUserByTweet {
			id
			userName
			profileBody
			iconPhoto
			isFollow: GetIsFollowByUser(userId: $userId)
		}
		isRetweet: GetIsRetweetByUser(userId: $userId)
		isLike: GetIsLikeByUser(userId: $userId)
		retweetCount: GetRetweetCount {
			count
		}
		likeCount: GetLikeCount {
			count
		}
		commentCount: GetCommentCount {
			count
		}
		comments: GetCommentsByTweet {
			id
			commentBody
			createdAt
			user: GetUserByComment {
				id
				userName
				profileBody
				iconPhoto
			}
		}
	}
}
