query GetTweetLikes($tweetId: Int!, $userId: String!) {
	tweet: GetTweet(id: $tweetId) {
		likes: GetLikesByTweet {
			id
			userId
			user: GetUserByLike {
				id
				userName
				profileBody
				isFollow: GetIsFollowByUser(userId: $userId)
			}
		}
	}
}
