query GetTweetRetweets($tweetId: Int!, $userId: String!) {
	tweet: GetTweet(id: $tweetId) {
		retweets: GetRetweetsByTweet {
			id
			userId
			user: GetUserByRetweet {
				id
				userName
				profileBody
				isFollow: GetIsFollowByUser(userId: $userId)
			}
		}
	}
}
