import Head from "next/head";
import Image from "next/image";

type ImageType = {
	name: string;
};

const Home = (props: ImageType) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1 className="text-red-400">
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				{props.name}

				<p>
					Get started by editing <code>pages/index.js</code>
				</p>

				<div>
					<a href="https://nextjs.org/docs">
						<h2>Documentation &rarr;</h2>
						<p>Find in-depth information about Next.js features and API.</p>
					</a>

					<a href="https://nextjs.org/learn">
						<h2>Learn &rarr;</h2>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</a>

					<a href="https://github.com/vercel/next.js/tree/master/examples">
						<h2>Examples &rarr;</h2>
						<p>Discover and deploy boilerplasssssss ss ssssss ssssssss sssss ss sssss te example Next.js projects.</p>
					</a>

					<a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
						<h2>Deploy &rarr;</h2>
						<p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
					</a>
				</div>
			</main>

			<footer>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

// eslint-disable-next-line import/no-default-export
export default Home;
