mutation UpdateProfile(
	$userId: String!
	$userName: String!
	$profileBody: String!
	$iconPhoto: String!
	$headerPhoto: String!
) {
	user: UpdateUser(
		id: $userId
		userDto: { userName: $userName, profileBody: $profileBody, iconPhoto: $iconPhoto, headerPhoto: $headerPhoto }
	) {
		id
		userName
		profileBody
		iconPhoto
		headerPhoto
	}
}
